#!/bin/sh

# /etc/init.d/ibtp: start and stop the IBTP service

NAME="ibtpserver"
DAEMON="/usr/bin/${NAME}"

ENABLE_SWFLAG_OFFSET=7
DAEMON_OPTS=""

die()
{
    echo $@
    exit 1
}

do_start()
{
    echo "Starting ${NAME} with opts: $IBTB_OPTS"

    export DISPLAY=:0
    start-stop-daemon -S -b -x "${DAEMON}" -- ${DAEMON_OPTS} 2>&1 | logger
    [ $? -ne 0 ] && die "Failed starting daemon"

    echo "."
}

do_stop()
{
    echo "Stopping ${NAME}"

    start-stop-daemon -K -x "${DAEMON}"
    [ $? -ne 0 ] && echo "Failed stopping daemon"

    echo "."
}

case "$1" in

  start)

    # IBTP Service is enabled at boot by a SWFlagArea bit
    if [ "$( cat /proc/$PPID/comm )" = "rc" ]; then
      . /etc/exorint.funcs

      [ $( exorint_swflagarea_bit $ENABLE_SWFLAG_OFFSET ) -eq 1 ] || exit
    fi

    do_start
    ;;

  stop)
    do_stop
    ;;

  restart)

    do_stop
    sleep 2
    do_start

    echo "."
    ;;

  *)
    echo "Usage: /etc/init.d/${NAME} {start|stop|restart}"
    exit 1
esac

exit 0
