#!/bin/sh

pidof EPAD >/dev/null || exit 0

dbus-send --print-reply --system --dest=com.exor.EPAD "/NetworkManager" com.exor.EPAD.NetworkManager.interfaceStateNotification string:"${dev}" int32:1

exit 0
