#!/bin/sh
ACTUALCONF=/etc/resolv.conf
PPPCONF=/var/run/ppp/resolv.conf
if [ -f $PPPCONF ] ; then
	if [ -f $ACTUALCONF ] ; then
		if [ ! -h $ACTUALCONF -o ! "`readlink $ACTUALCONF 2>&1`" = "$PPPCONF" ] ; then
			sed -i '1i # From PPP provider' $PPPCONF  # prepended
			echo '# Original config' >> $PPPCONF
			cat $ACTUALCONF >> $PPPCONF
			mv $ACTUALCONF $ACTUALCONF.ppporig
		fi
	fi

	ln -sf $PPPCONF $ACTUALCONF
fi
