#!/bin/sh
MOBILE_APN=`/usr/bin/sys_params services/mobile/apn`

cat << EOF
# *PLEASE DO NOT MODIFY* - Automatically generated by '$(basename $0)'

# You can use this script unmodified to connect to cellular networks.
# The APN is specified in the peers file as the argument of the -T command
# line option of chat(8).

# For details about the AT commands involved please consult the relevant
# standard: 3GPP TS 27.007 - AT command set for User Equipment (UE).
# (http://www.3gpp.org/ftp/Specs/html-info/27007.htm)

ABORT       BUSY
ABORT       VOICE
ABORT       "NO CARRIER"
ABORT       "NO DIALTONE"
ABORT       "NO DIAL TONE"
ABORT       "NO ANSWER"
ABORT       "DELAYED"
ABORT       "ERROR"

# cease if the modem is not attached to the network yet
ABORT       "+CGATT: 0"

""          AT
TIMEOUT     30

OK          ATH
OK          ATE1
# DTR usage not available - disable it
OK          AT&D0

#OK          AT+CGDCONT=1,"IP","\T","",0,0
OK          AT+CGDCONT=1,"IP","${MOBILE_APN}","0.0.0.0",0,0

#OK          ATD*99#
OK          ATD*99***1#

CONNECT     ""
EOF
